import math

TILESIZE = 64
WALL_SIZE = TILESIZE # better maybe 32 FIXME

ROWS = 10
COLS = 15

WIDTH = COLS * TILESIZE
HEIGHT = ROWS * TILESIZE

FOV = 60 * (math.pi / 180)

RES = 4
NUM_RAYS = WIDTH // RES
PRECISION_FIX_GAPS = 0.0001